#!/bin/bash

#Provide some basic features and
#Redirect groan <cmd> to groan.<cmd>.cmd.sh

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob # make sure globs are empty arrays if nothing is foound

# our contribution to help
commonOptions="common options:
--help    | -h | -?  Usage help for a command
--quiet   | -q       Quiet mode - say nothing
--verbose | -V       Verbose
--debug   | -d | -D  Debug - tell all
--dry-run            # default
--confirm            # not a dry run - perform action
"

#default flags
DEBUG=false
VERBOSE=false
LOUD=true
DRYRUN=true
CONFIRM=false
SHOWHELP=false #exec command and only display the help metadata
METADATAONLY=false #exec command only as far as the help metadata

#search through the arguments for the command and flags
args=()
command=""
for arg in "$@"
do
	case "$arg" in
	  --debug | -d | -D)
	    	DEBUG=true
	    	VERBOSE=true
	    	LOUD=true
	    ;;
	  --help | -h | "-?")
	  		SHOWHELP=true
	  		METADATAONLY=true
	    ;;
	  --verbose | --v | -v | -V )
	    	DEBUG=false
	    	VERBOSE=true
	    	LOUD=true
	   ;;
	   --quiet | -q)
	    	LOUD=false
	    	DEBUG=false
	    	VERBOSE=false
	    ;;
	    --dry-run | -dry | --dry)
	    	DRYRUN=true
	    	CONFIRM=false
	    ;;
	    --confirm)
	    	DRYRUN=false
	    	CONFIRM=true
	    ;;
	    *)
		if [[ "$command" = "" ]]; then
		   command=$arg
		else
		   args+=($arg)
		fi
	    ;;
	esac
	shift
done

#find platform

MACOSX=false
WINDOWS=false
UNIX=false
system=$(uname)

if [[  -d "/System/Library/Frameworks" ]] ; then
	MACOSX=true
elif [ -d "/WINDOWS" ] ; then
	WINDOWS=true
else
	UNIX=true
fi

#find the $scriptFile and importantly the $scriptDir
scriptFile="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
if [ -L "$scriptFile" ]; then
	scriptFile=`readlink -n $scriptFile`
fi
scriptName=${scriptFile##*/} # `basename $scriptFile` 
scriptDir=${scriptFile%/*} # `dirname $scriptFile`
workingDir=$(pwd)
searchablePath=":$PATH:"

$VERBOSE &&	echo "name:$scriptName		file:$scriptFile	dir:$scriptDir	"
$VERBOSE && echo "command:$command		working:$workingDir" 		

source "$scriptDir/$scriptName.locations"

for configFile in ${configFileLocations[@]}
do
	if [[ -f $configFile ]]; then
		$VERBOSE && echo "using configuration: $configFile"
		source "$configFile"
		break
	fi
done

# no command provided default to subcommmand help --help
if [[ "$command" = "" ]]; then
	echo
	sh $scriptFile help --help
	exit
fi

target="$scriptName.${command}*.cmd.*"

count=0
previous=""
for loc in ${locations[@]} 
do
	[[ "$previous" == "$loc" ]] && break
	previous="$loc"
	
	$DEBUG && echo "looking in: $loc"

	for found in $loc/$target
	do
		count=$((count + 1))	
		$DEBUG && echo "found #$count : $found"
	done

	if [ $count -gt 1 ]; then
		$LOUD && echo "Warning: Command '$command' is ambiguous (use --debug for more info)"
		exit
	fi

	arg_str="${args[@]:+${args[@]}}" # needed bash<=4.1 when set -u is on
	
	for found in $loc/$target
	do
		case ${found##*.} in
			sh)
				$DEBUG && echo "running source: $found $arg_str"
				source "$found" "${args[@]:+${args[@]}}"
			;;
			exec)
				$DEBUG && echo "running exec: $found $arg_str"
				exec "$found" "${args[@]:+${args[@]}}"
			;;
			*)
				$DEBUG && echo "running eval: $found $arg_str"
				#evaluate meta-data first
				eval "$(sed -n 's|^#m# \(.*\)$|\1|p' $found)"
				
				eval "$found" "${args[@]:+${args[@]}}"
			;;
		esac
		exit
	done
done

$LOUD && echo "Warning: $scriptName sub-command $command not found"
exit 1

#"This Code is distributed subject to the MIT License, as in http://www.opensource.org/licenses/mit-license.php . 
#Any additional contribution submitted for incorporation into or for distribution with this file shall be presumed subject to the same license."